---
output: 
  pdf_document:
    latex_engine: xelatex

geometry: margin=1.9cm 
mainfont: Calibri  # Use Ubuntu as mainfont if on Ubuntu-based linux, same idea for Mac

params:
  produto: "default"
  month: "default"
  year: "default"


header-includes:
- \usepackage{atbegshi}
- \AtBeginDocument{\AtBeginShipoutNext{\AtBeginShipoutDiscard}{\addtocounter{page}{-1}}}
- \usepackage{pdflscape}
- \newcommand{\blandscape}{\begin{landscape}}
- \newcommand{\elandscape}{\end{landscape}}
- \usepackage{booktabs}
- \usepackage{longtable}
- \usepackage{array}
- \usepackage{multirow}
- \usepackage{wrapfig}
- \usepackage{float}
- \usepackage{colortbl}
- \usepackage{pdflscape}
- \usepackage{tabu}
- \usepackage{threeparttable}
- \usepackage{threeparttablex}
- \usepackage[normalem]{ulem}
- \usepackage{makecell}
- \usepackage{xcolor}
---
  
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  error = FALSE
)
```


```{r child = here::here("www/rmarkdown/front_page.Rmd")}

```

\newpage

```{r child = here::here("www/rmarkdown/pagina_um.Rmd")}

```

\newpage

```{r child = here::here("www/rmarkdown/pagina_dois.Rmd")}

```

\newpage

```{r child = here::here("www/rmarkdown/best_customer.Rmd")}

```

\newpage

```{r child = here::here("www/rmarkdown/back.Rmd")}

```